global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rag-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rag-app:8000"]
        labels:
          service: "kubernetes-rag"
          environment: "dev"
    scrape_interval: 10s
